Using device: cuda:1
Epoch 1/50
  0%|                                                                                                                                     | 0/164 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    train(net, args)
  File "train.py", line 72, in train
    output = net(t1_img, t2_img)
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 1.
Original Traceback (most recent call last):
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home_ext/whm_ext/hcq/7/flood_unet/network/model.py", line 77, in forward
    s2_feature = self.s2_stream(t2_img)
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home_ext/whm_ext/hcq/7/flood_unet/network/reunet.py", line 107, in forward
    x8 = self.upsample_3(x8)
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home_ext/whm_ext/hcq/7/flood_unet/network/reunet.py", line 40, in forward
    return self.upsample(x)
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home_ext/whm_ext/miniconda3/envs/camera/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 916, in forward
    return F.conv_transpose2d(
RuntimeError: CUDA out of memory. Tried to allocate 704.00 MiB (GPU 1; 23.68 GiB total capacity; 20.86 GiB already allocated; 203.81 MiB free; 21.96 GiB reserved in total by PyTorch)