2024-07-24 17:54:54,958 INFO    MainThread:31700 [internal.py:wandb_internal():90] W&B internal server running at pid: 31700, started at: 2024-07-24 17:54:54.957815
2024-07-24 17:54:54,960 DEBUG   HandlerThread:31700 [handler.py:handle_request():140] handle_request: run_start
2024-07-24 17:54:54,962 INFO    WriterThread:31700 [datastore.py:open_for_write():75] open: /home_ext/whm_ext/hcq/7/flood_unet/wandb/offline-run-20240724_175454-jp4pbj65/run-jp4pbj65.wandb
2024-07-24 17:54:54,991 DEBUG   HandlerThread:31700 [meta.py:__init__():35] meta init
2024-07-24 17:54:54,991 DEBUG   HandlerThread:31700 [meta.py:__init__():49] meta init done
2024-07-24 17:54:54,991 DEBUG   HandlerThread:31700 [meta.py:probe():209] probe
2024-07-24 17:54:54,997 DEBUG   HandlerThread:31700 [git.py:repo():29] git repository is invalid
2024-07-24 17:54:54,998 DEBUG   HandlerThread:31700 [meta.py:_save_pip():53] save pip
2024-07-24 17:54:54,999 DEBUG   HandlerThread:31700 [meta.py:_save_pip():67] save pip done
2024-07-24 17:54:54,999 DEBUG   HandlerThread:31700 [meta.py:_save_conda():74] save conda
2024-07-24 17:55:07,907 DEBUG   HandlerThread:31700 [meta.py:_save_conda():84] save conda done
2024-07-24 17:55:07,908 DEBUG   HandlerThread:31700 [meta.py:probe():247] probe done
2024-07-24 17:55:58,911 WARNING MainThread:31700 [internal.py:wandb_internal():153] Internal process interrupt: 1
2024-07-24 17:56:00,914 WARNING MainThread:31700 [internal.py:is_dead():387] Internal process exiting, parent pid 31167 disappeared
2024-07-24 17:56:00,914 ERROR   MainThread:31700 [internal.py:wandb_internal():149] Internal process shutdown.
2024-07-24 17:56:00,978 INFO    SenderThread:31700 [sender.py:finish():1114] shutting down sender
2024-07-24 17:56:01,743 INFO    WriterThread:31700 [datastore.py:close():279] close: /home_ext/whm_ext/hcq/7/flood_unet/wandb/offline-run-20240724_175454-jp4pbj65/run-jp4pbj65.wandb
2024-07-24 17:56:01,745 INFO    HandlerThread:31700 [handler.py:finish():806] shutting down handler
2024-07-24 17:56:01,746 INFO    MainThread:31700 [internal.py:handle_exit():80] Internal process exited
